# Generated by Django 5.0.7 on 2024-11-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(default=None, max_length=35, null=True)),
            ],
            options={
                'db_table': 'coach',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=35)),
                ('description', models.TextField(default=None, null=True)),
                ('coach', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lending.coach')),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lending.country')),
            ],
            options={
                'db_table': 'club',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(default=None, max_length=35, null=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('club', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='lending.club')),
                ('country_of_birth', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lending.country')),
            ],
            options={
                'db_table': 'player',
                'ordering': ['id'],
            },
        ),
    ]
