# Generated by Django 5.0.7 on 2024-12-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_coach_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='clubs/'),
        ),
        migrations.AddField(
            model_name='coach',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='coaches/'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='players/'),
        ),
    ]
