# Generated by Django 5.0.7 on 2024-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_club_photo_coach_photo_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=35, null=True),
        ),
    ]
