# Generated by Django 5.0.7 on 2024-12-26 15:33

import lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_alter_coach_middle_name_alter_player_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=lending.models.upload_files),
        ),
    ]
